title: RafiOffsec
description: "Researching the Depths of Hacking and Cybersecurity"
author:
  name: "Muhammad_Rafi_Akbar"
  email: "rafioffsec@proton.me"
  url: "https://rafioffsec.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "SomeHacker"
year : "2020"
